name: DA DP Tag and pre deploy Holding Verification App
on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "README.md"
      - ".gitignore"
      - "config.ini"
      - "test/**"

permissions:
  id-token: write
  contents: write
jobs:
  generate-exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.14'
      - id: next-tag
        shell: python
        run: |
          import json, os, urllib.request, configparser

          url = f"{os.environ['GITHUB_API_URL']}/repos/nationalarchives/da-dp-holding-verification/tags"
          headers = {"Accept": "application/vnd.github+json", "Authorization": f"Bearer {os.getenv("GH_TOKEN")}"}

          tag_num = json.load(urllib.request.urlopen(urllib.request.Request(url, headers=headers)))[0]["name"][1:]
          current_version_split = tag_num.split(".")

          config = configparser.ConfigParser()
          config.read("config.ini")
          default_config = config["DEFAULT"]
          config_app_version = default_config["APP_VERSION"]
          app_version_split = config_app_version.split(".")
          new_version_is_higher = False

          for a_num, c_num in zip(app_version_split, current_version_split):
            if int(a_num) > int(c_num):
              new_version_is_higher = True
              break

          if new_version_is_higher:
              with open(os.environ["GITHUB_OUTPUT"], "a") as go:
                  go.write(f"next-version=v{config_app_version}\n")
          else:
            raise Exception(
                f"New app version defined in 'config.ini' {config_app_version} " +
                f"is not higher than the current {tag_num} version"
            )
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Upgrade pip & create exe file
        run: |
          python -m pip install --upgrade pip
          Invoke-WebRequest https://raw.githubusercontent.com/Eliav2/tkinterdnd2/refs/heads/master/hook-tkinterdnd2.py -OutFile .\hook-tkinterdnd2.py
          pip install -r requirements.txt
          pyinstaller --icon=".\folder_smile.ico" holding_verification.py --additional-hooks-dir=.
          Copy-Item -Path config.ini -Destination dist/holding_verification
          mkdir zipped_executable
          Compress-Archive -Path dist/* -Destination zipped_executable/da-holding-verification-windows-64.zip
          gh release create --generate-notes ${{ steps.next-tag.outputs.next-version }} zipped_executable/da-holding-verification-windows-64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
